version = 1

test_patterns = ["sophie_bot/**.py"]

exclude_patterns = ["sophie_bot/modules/legacy_modules/**"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]

[[transformers]]
name = "yapf"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"