image: jdrouet/docker-with-buildx:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: "$CI_REGISTRY_IMAGE"
  IMAGE_TAG: "$CI_COMMIT_BRANCH"
  IMAGE_FULL: "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH"


stages:
  - test
  - build

python:flake8:
  image: python:latest
  stage: test
  allow_failure: true
  before_script:
    - pip install flake8
    - pip install --force-reinstall git+https://github.com/pycqa/pyflakes
  script:
    - cd /builds/SophieBot/sophie/
    - python3 -m flake8 sophie_bot --max-line-length=120 --ignore=E203,E231,E701 | tee flake8-report.txt
  artifacts:
    paths: [ flake8-report.txt ]


build_container:
  tags:
    - saas-linux-medium-amd64
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker buildx create --use
    - docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag "$IMAGE_FULL" .