- name: Update Current branch WIKI podman image
  containers.podman.podman_image:
    name: "{{ lookup('ansible.builtin.env','IMAGE_NAME') }}"
    tag: "{{ lookup('ansible.builtin.env','BRANCH') }}-wiki"
    force: true

- name: Copy Current branch WIKI container quadlet file
  vars:
    image_tag: "{{ lookup('ansible.builtin.env','BRANCH') }}-wiki"
  ansible.builtin.template:
    src: swiki.container.j2
    dest: /home/containers/.config/containers/systemd/swiki.container
    owner: containers
    group: containers
    mode: u=rw,g=r,o=r

- name: Restart Wiki container
  ansible.builtin.systemd_service:
    scope: user
    state: restarted
    daemon_reload: true
    name: swiki
