- name: Copy wiki docs
  ansible.builtin.copy:
    src: "../../wiki_docs"
    dest: /var/sophie/
    owner: containers
    group: containers
    mode: u=rw,g=r,o=r
    force: true

- name: Update Current branch WIKI podman image
  containers.podman.podman_image:
    name: "registry.gitlab.com/orangefox/infrastructure/foxbox"
    tag: "foxwiki-master"
    force: true

- name: Copy Current branch WIKI container quadlet file
  vars:
    image_name: "registry.gitlab.com/orangefox/infrastructure/foxbox"
    image_tag: "foxwiki-master"
  ansible.builtin.template:
    src: swiki.container.j2
    dest: /home/containers/.config/containers/systemd/swiki.container
    owner: containers
    group: containers
    mode: u=rw,g=r,o=r

- name: Copy Wiki env file
  ansible.builtin.template:
    src: swiki.env.j2
    dest: /var/sophie/swiki.env
    owner: containers
    group: containers
    mode: u=rw,g=r,o=r

- name: Restart Wiki container
  ansible.builtin.systemd_service:
    scope: user
    state: restarted
    daemon_reload: true
    name: swiki
