- name: Set vars for Staging
  set_fact:
    token: "{{ lookup('env', 'BETA_TOKEN') }}"
    username: "{{ lookup('env', 'BETA_USERNAME') }}"
    sentry_url: "{{ lookup('env', 'STAGING_SENTRY') }}"
    tavily_key: "{{ lookup('env', 'TAVILY_KEY') }}"
    mistral_key: "{{ lookup('env', 'MISTRAL_API_KEY') }}"
    openrouter_api_key: "{{ lookup('env', 'OPENROUTER_API_KEY') }}"
    role: "staging"
  when: inventory_hostname == "sstaging"

- name: Set vars for Prod
  set_fact:
    token: "{{ lookup('env', 'STABLE_TOKEN') }}"
    username: "{{ lookup('env', 'STABLE_USERNAME') }}"
    sentry_url: "{{ lookup('env', 'PROD_STABLE_SENTRY') }}"
    tavily_key: "{{ lookup('env', 'TAVILY_KEY') }}"
    mistral_key: "{{ lookup('env', 'MISTRAL_API_KEY') }}"
    openrouter_api_key: "{{ lookup('env', 'OPENROUTER_API_KEY') }}"
    role: "production"
  when: inventory_hostname == "white"